server {
    listen 80;
    server_name 10.2.2.41; # O el dominio si tienen uno interno en ARSA

    # Redirigir todo a HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name 10.2.2.41;

    # Certificados (Aquí pondrías los que generes)
    ssl_certificate /etc/nginx/certs/arsa_server.crt;
    ssl_certificate_key /etc/nginx/certs/arsa_server.key;

    location / {
        proxy_pass http://flask_app:5000; # Nombre del servicio en docker
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Esto es vital para las cookies que configuramos antes
        proxy_cookie_path / "/; HTTPOnly; Secure; SameSite=None";
    }
}